### ISSUE TITLE
Please actualize usage descriptions

### ISSUE THREAD

**Issue by puinenveturi** [mattfenwick/NMRPyStar#3]
Please update the brief description on useage, upon a recent git clone, nmpstar.parse stopped working:

```
>>> import nmrpystar
>>> parsed = nmrpystar.parse(myString)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'parse'
```

My program use NMRPyStar to parse STR and since this update the code is broken as I've pip installed the module on a clean system.

**Comment by kmckiern** [comment]
Any update to this?

**Comment by derPuntigamer** [comment]
I stick to v0.0.15 where the following code works:

```python
def parseSTR(STR_file):
    """Parse BMRB file into a python object"""
    star_file = open(STR_file)         # open STR file
    myString = ""

    for line in star_file:                  # rean STR file into a string
        myString += line

    star_file.close()
    parsed = nmrpystar.parse(myString)      # parsing -> parsed.value

    if parsed.status != 'success':          # check if parsing was successful
        print('Error during STR parsing: ', parsed)
        raise SystemExit
    else:
        return parsed
```

in the current version, the following error occurs with the same code and STAR-NMR file:

```
>>> parsed = nmrpystar.parse(myString)
>>> parsed.status
'error'
>>> parsed
{'status': 'error', 'type': 'MaybeError', 'value': {'phase': 'CST construction', 'message': [('data block', (6, 1))]}}
```

the used example file is: http://users.itk.ppke.hu/~dudda/calculations/dummy.str

From the example code, I couldn't figure it out, why my code no more works with the new version.

**Comment by leeping** [comment]
Hello - I am also a bit puzzled as to why nmrpystar.parse() is no longer working.

**Comment by derPuntigamer** [comment]
I was trying to use nmrpystar from pip install, I have neither parse() nor parser() in the module:

```
>>> dir(nmrpystar)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__']
```

@mattfenwick could you please update the pip version of the module?

**Comment by mattfenwick** [comment]
@derPuntigamer I'm looking into this ... sorry for not seeing this for so long. :(

**Comment by mattfenwick** [comment]
apologize for the delay ... @puinenveturi would be happy to add you as a maintainer if you're still using this!

**Comment by puinenveturi** [comment]
@mattfenwick This is still my favourite STR parser! I don't know the internals but I am interested in keeping this lib compatible with newer versions of Python :)

**Comment by mattfenwick** [comment]
@puinenveturi awesome , glad you like it!!  I just sent you an invite to the repo 👍 

I'm tracking the work to get NMRPyStar back on track here https://github.com/mattfenwick/NMRPyStar/issues/6 , if there's anything else that needs to be done feel free to add it there!

My goal is to turn this around in less than 2 weeks (you're welcome to help out anywhere!) so please yell at me if I forget again!

**Comment by puinenveturi** [comment]
Examples code looks and words fine now after merging #8 
I would consider including a basic usage example in the README like:

``` python
import nmrpystar

# read and parse data from STAR-NMR file
with open("examples/bmrb17661.txt") as str_file:
    str_string = str_file.read()
    parsed = nmrpystar.parse_nmrstar_ast(str_string)

# get chemical shifts frame data
chemShiftSave = parsed.value.saves["assigned_chem_shift_list_1"]
loopShifts = chemShiftSave.loops['Atom_chem_shift']

# loop through chemical shifts frame data
for entry in range(len(loopShifts.rows)):
    row = loopShifts.getRowAsDict(entry)
    key = (row['Comp_ID'], row['Atom_ID'], row['Val'])

    # process / show 
    print(key)
```
