### ISSUE TITLE
Please do not use relative import in example code

### ISSUE THREAD

**Issue by puinenveturi** [mattfenwick/NMRPyStar#4]
Using relative imports in examples makes it more difficult to import NMRPyStar and get the included functions works. You can use your own PIP package as a reference.

**Comment by mattfenwick** [comment]
@derPuntigamer thanks for pointing this out!  I'd be happy to merge a PR if you put one together, otherwise I'll try to get to soon!

**Comment by derPuntigamer** [comment]
@mattfenwick I can make a PR, but last time I have tried, I could not get nmrpystar to parse my files, so I have created a copy in my project internally. I would be happy to help to get this straight and be able to use nmrpystar from pip.

**Comment by mattfenwick** [comment]
This should be fixed in https://github.com/mattfenwick/NMRPyStar/pull/8 !
